Gerenciador-de-Inventario-MVC/Controllers/EmployeeController.cs
using Application.DTO;
using Application.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shared.Helper.Services.Interface;

namespace Gerenciador_de_Inventario_MVC.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly IViewRenderService _viewRenderService;
        private ResponseDTO _responseDTO;

        public EmployeeController(IEmployeeService employeeService,
            IViewRenderService viewRenderService)
        {
            _employeeService = employeeService;
            _viewRenderService = viewRenderService;
            _responseDTO = new ResponseDTO();
        }

        public IActionResult Index()
        {
            try
            {
                EmployeeDTO employeeDTO = _employeeService.GetEmployee();
                return View(employeeDTO);
            } catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public IActionResult Form(int id)
        {
            try
            {
                EmployeeDTO employeeDTO = _employeeService.FormEmployee(id);
                _responseDTO.View = _viewRenderService.RenderToString(this, "_Form", employeeDTO);
                return Json(_responseDTO);
            } catch (Exception)
            {
                _responseDTO.StatusErro = true;
                _responseDTO.Message = "Ops, tivemos um problema interno, não foi possível abrir o formulário!";
                return Json(_responseDTO);
            }
        }

        public IActionResult Save(EmployeeDTO employeeDTO)
        {
            try
            {
                employeeDTO = _employeeService.SaveEmploye(employeeDTO);
                if (employeeDTO.StatusErroMessage)
                {
                    _responseDTO.StatusErro = true;
                    _responseDTO.Message = employeeDTO.Message;
                    return Json(_responseDTO);
                }

                _responseDTO.Message = employeeDTO.Message;
                _responseDTO.View = _viewRenderService.RenderToString(this, "_TableEmployee", employeeDTO);
                return Json(_responseDTO);
            } catch (Exception)
            {
                _responseDTO.StatusErro = true;
                _responseDTO.Message = "Ops, tivemos um problema interno, não foi possível gravar sua solicitação!";
                return Json(_responseDTO);
            }
        }

        public IActionResult Detail(int id)
        {
            try
            {
                EmployeeDTO employeeDTO = _employeeService.FormEmployee(id);
                _responseDTO.View = _viewRenderService.RenderToString(this, "_Detail", employeeDTO);
                return Json(_responseDTO);
            } catch (Exception)
            {
                _responseDTO.StatusErro = true;
                _responseDTO.Message = "Ops, tivemos um problema interno, não foi possível abrir o detalhar!";
                return Json(_responseDTO);
            }
        }

        public IActionResult Delete(int id)
        {
            try
            {
                EmployeeDTO employeeDTO = _employeeService.DeleteEmploye(id);
                if (employeeDTO.StatusErroMessage)
                {
                    _responseDTO.StatusErro = true;
                    _responseDTO.Message = employeeDTO.Message;
                    return Json(_responseDTO);
                }

                _responseDTO.View = _viewRenderService.RenderToString(this, "_TableEmployee", employeeDTO);
                return Json(_responseDTO);
            } catch (Exception)
            {
                _responseDTO.StatusErro = true;
                _responseDTO.Message = "Ops, tivemos um problema interno, não foi possível atender sua solicitação";
                return Json(_responseDTO);
            }
        }
    }
}

Gerenciador-de-Inventario-MVC/Controllers/ProductController.cs
using Application.DTO;
using Application.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shared.Helper.Services.Interface;

namespace Gerenciador_de_Inventario_MVC.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly IViewRenderService _viewRenderService;
        private ResponseDTO _responseDTO;

        public ProductController(IProductService productService,
            IViewRenderService viewRenderService)
        {
            _productService = productService;
            _viewRenderService = viewRenderService;
            _responseDTO = new ResponseDTO();
        }

        public IActionResult Index()
        {
            try
            {
                ProductDTO productDTO = _productService.GetProduct();
                return View(productDTO);
            } catch (Exception)
            {
               return RedirectToAction("Index", "Home");
            }
        }

        public IActionResult Form(int id)
        {
            try
            {
                ProductDTO productDTO = _productService.FormProduct(id);
                _responseDTO.View = _viewRenderService.RenderToString(this, "_Form", productDTO);
                return Json(_responseDTO);
            } catch (Exception)
            {
                _responseDTO.StatusErro = true;
                _responseDTO.Message = "Ops, tivemos um problema interno, não foi possível abrir o formulário!";
                return Json(_responseDTO);
            }
        }

        public IActionResult Save(ProductDTO productDTO)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    _responseDTO.StatusErro = true;
                    _responseDTO.View = _viewRenderService.RenderToString(this, "_PartialForm", productDTO);
                    return Json(_responseDTO);
                }

                productDTO = _productService.SaveProduct(productDTO);
                if (productDTO.StatusErroMessage)
                {
                    _responseDTO.StatusErro = true;
                    _responseDTO.Message = productDTO.Message;
                    return Json(_responseDTO);
                }

                _responseDTO.Message = productDTO.Message;
                _responseDTO.View = _viewRenderService.RenderToString(this, "_TableProduct", productDTO);
                return Json(_responseDTO);
            } catch (Exception)
            {
                _responseDTO.StatusErro = true;
                _responseDTO.Message = "Ops, tivemos um problema interno, não foi possível gravar sua solicitação!";
                return Json(_responseDTO);
            }
        }

        public IActionResult Detail(int id)
        {
            try
            {
                ProductDTO productDTO = _productService.FormProduct(id);
                _responseDTO.View = _viewRenderService.RenderToString(this, "_Detail", productDTO);
                return Json(_responseDTO);
            } catch (Exception)
            {
                _responseDTO.StatusErro = true;
                _responseDTO.Message = "Ops, tivemos um problema interno, não foi possível abrir o detalhar!";
                return Json(_responseDTO);
            }
        }

        public IActionResult Delete(int id)
        {
            try
            {
                ProductDTO productDTO = _productService.DeleteProduct(id);
                if (productDTO.StatusErroMessage)
                {
                    _responseDTO.StatusErro = true;
                    _responseDTO.Message = productDTO.Message;
                    return Json(_responseDTO);
                }

                _responseDTO.View = _viewRenderService.RenderToString(this, "_TableProduct", productDTO);
                return Json(_responseDTO);
            } catch (Exception)
            {
                _responseDTO.StatusErro = true;
                _responseDTO.Message = "Ops, tivemos um problema interno, não foi possível atender sua solicitação";
                return Json(_responseDTO);
            }
        }
    }
}

Gerenciador-de-Inventario-MVC/Controllers/StockMovementsController.cs
using Application.DTO;
using Application.Interfaces;
using Data.Repositories;
using Domain.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shared.Helper.Services.Interface;

namespace Gerenciador_de_Inventario_MVC.Controllers
{
    [Authorize]
    public class StockMovementsController : Controller
    {
        private readonly IStockMovementsService _stockMovementsService;
        private readonly IViewRenderService _viewRenderService;
        private readonly IEmployeeRepository _employeeRepository;
        private ResponseDTO _responseDTO;

        public StockMovementsController(IStockMovementsService stockMovementsService,
            IEmployeeRepository employeeRepository,
            IViewRenderService viewRenderService)
        {
            _stockMovementsService = stockMovementsService;
            _employeeRepository = employeeRepository;
            _viewRenderService = viewRenderService;
            _responseDTO = new ResponseDTO();
        }

        public IActionResult Index()
        {
            try
            {
                StockMovementsDTO stockMovementsDTO = _stockMovementsService.GetStockMovements();
                return View(stockMovementsDTO);
            } catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public IActionResult Form()
        {
            try
            {
                StockMovementsDTO stockMovementsDTO = _stockMovementsService.FormProductInStock();
                _responseDTO.View = _viewRenderService.RenderToString(this, "_Form", stockMovementsDTO);
                return Json(_responseDTO);
            } catch (Exception)
            {
                _responseDTO.StatusErro = true;
                _responseDTO.Message = "Ops, tivemos um problema interno, não foi possível abrir o formulário!";
                return Json(_responseDTO);
            }
        }

        public IActionResult FormRemove()
        {
            try
            {
                StockMovementsDTO stockMovementsDTO = _stockMovementsService.FormRemoveProductInStock();
                _responseDTO.StatusErro = false;
                _responseDTO.View = _viewRenderService.RenderToString(this, "_FormRemove", stockMovementsDTO);
                return Json(_responseDTO);
            } catch (Exception)
            {
                _responseDTO.StatusErro = true;
                _responseDTO.Message = "Ops, tivemos um problema interno, não foi possível abrir o formulário!";
                return Json(_responseDTO);
            }
        }

        public IActionResult Save(StockMovementsDTO stockMovementsDTO)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    _responseDTO.StatusErro = true;
                    _responseDTO.View = _viewRenderService.RenderToString(this, "_PartialForm", stockMovementsDTO);
                    return Json(_responseDTO);
                }

                stockMovementsDTO = _stockMovementsService.AddProductInStock(stockMovementsDTO);
                if (stockMovementsDTO.StatusErroMessage)
                {
                    _responseDTO.StatusErro = true;
                    _responseDTO.Message = stockMovementsDTO.Message;
                    return Json(_responseDTO);
                }

                _responseDTO.Message = stockMovementsDTO.Message;
                _responseDTO.View = _viewRenderService.RenderToString(this, "_TableStockMovements", stockMovementsDTO);
                return Json(_responseDTO);
            } catch (Exception)
            {
                _responseDTO.StatusErro = true;
                _responseDTO.Message = "Ops, tivemos um problema interno, não foi possível gravar sua solicitação!";
                return Json(_responseDTO);
            }
        }

        public IActionResult Remove(StockMovementsDTO stockMovementsDTO)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    _responseDTO.StatusErro = true;
                    _responseDTO.View = _viewRenderService.RenderToString(this, "_PartialFormRemove", stockMovementsDTO);
                    return Json(_responseDTO);
                }

                stockMovementsDTO = _stockMovementsService.RemoveProductInStock(stockMovementsDTO);
                if (stockMovementsDTO.StatusErroMessage)
                {
                    _responseDTO.StatusErro = true;
                    _responseDTO.Message = stockMovementsDTO.Message;
                    return Json(_responseDTO);
                }

                _responseDTO.Message = stockMovementsDTO.Message;
                _responseDTO.View = _viewRenderService.RenderToString(this, "_TableStockMovements", stockMovementsDTO);
                return Json(_responseDTO);
            } catch (Exception)
            {
                _responseDTO.StatusErro = true;
                _responseDTO.Message = "Ops, tivemos um problema interno, não foi possível gravar sua solicitação!";
                return Json(_responseDTO);
            }
        }

        public IActionResult Detail(int id)
        {
            try
            {
                StockMovementsDTO stockMovementsDTO = _stockMovementsService.DetailProductInStock(id);
                if (stockMovementsDTO.StatusErroMessage)
                {
                    _responseDTO.StatusErro = true;
                    _responseDTO.Message = stockMovementsDTO.Message;
                    return Json(_responseDTO);
                }

                _responseDTO.View = _viewRenderService.RenderToString(this, "_Detail", stockMovementsDTO);
                return Json(_responseDTO);
            } catch (Exception)
            {
                _responseDTO.StatusErro = true;
                _responseDTO.Message = "Ops, tivemos um problema interno, não foi possível abrir o formulário!";
                return Json(_responseDTO);
            }
        }
    }
}

Gerenciador-de-Inventario-MVC/Views/Shared/_Layout.cshtml
@{
    int year = DateTime.Now.Year;
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Gerenciador de Inventário</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <!-- DataTables CSS -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.1/css/buttons.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.5.0/css/responsive.dataTables.min.css">

    <!-- Material Symbols -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />

    <!-- Sweetalert2 -->
    <link rel="stylesheet" href="~/lib/sweetalert2/sweetalert2.min.css" />
    <link rel="stylesheet" href="~/lib/sweetalert2/sweetalert2.css" />

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>

    <!-- DataTables JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.5.0/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.print.min.js"></script>

    <!-- Custom Scripts -->
    <script src="~/js/DataTableHelper.js" asp-append-version="true"></script>
    <script src="~/js/ModalHelper.js" asp-append-version="true"></script>
    <script src="~/lib/sweetalert2/sweetalert2.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gerenciador de Inventário</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">
                                <span class="material-symbols-outlined">group</span> Funcionários
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PermissionGroup" asp-action="Index">
                                <span class="material-symbols-outlined">security</span> Grupo de Permissão
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">
                                <span class="material-symbols-outlined">shopping_cart</span> Produtos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StockMovements" asp-action="Index">
                                <span class="material-symbols-outlined">inventory</span> Movimentação do Estoque
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" onclick="OpenFormRemoveProductInStock()" style="cursor: pointer;">
                                <span class="material-symbols-outlined">sell</span> Venda
                            </a>
                        </li>
                    </ul>

                    <!-- Botão Logout -->
                    <form method="post" asp-controller="Login" asp-action="Logout">
                        <button type="submit" class="btn btn-danger">Logout</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container d-flex justify-content-center align-items-center">
            &copy; @year - Gerenciador de Inventário
        </div>
    </footer>

    <!-- Razor Scripts -->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Gerenciador-de-Inventario-MVC/Views/Shared/_LayoutLoggedOut.cshtml
@{
    int year = DateTime.Now.Year;
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login - Gerenciador de Inventário</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <!-- Material Symbols -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />

    <!-- Sweetalert2 -->
    <link rel="stylesheet" href="~/lib/sweetalert2/sweetalert2.min.css" />
    <link rel="stylesheet" href="~/lib/sweetalert2/sweetalert2.css" />

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>

    <!-- Custom Scripts -->
    <script src="~/lib/sweetalert2/sweetalert2.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Razor Scripts -->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>